### ISSUE TITLE
CometConfig

### ISSUE THREAD

**Issue by dcsan** [Strngs/comet#10]
is there an example CometConfig anywhere? more specifically are there any differences from the AdminConfig of yogiben:admin?

I guess this is the main reference for now.
https://github.com/yogiben/meteor-admin/pull/58
https://github.com/WillHall/meteor-starter/blob/master/both/config/adminConfig.coffee

keen to try out the Datatables, but is it still way too early to use this?

**Comment by WillHall** [comment]
Datatables work in the adminPR if you model your config after the one in my meteor-starter yes.

I am holding off on a readme for comet because I am doing custom interactive widgets and such, and adding a superadmin role as well.

**Comment by dcsan** [comment]
OK well looks like there are conflicts in the PR so i may need to wait for a merge.
is there a specific branch in your meteor-admin repo I could pull from?

**Comment by WillHall** [comment]
Broken by https://github.com/yogiben/meteor-admin/pull/54 :(

Master is where I committed the config changes for meteor starter.

You should be able to use that branch plus comet instead of admin, however you will need to change AdminConfig to CometConfig in the file.

Comet is iterating quickly - so use the one in atmosphere to check out the reactive tables. I should have a major update for Comet in the next week, at that time I will focus on getting docs written up.
